### ISSUE TITLE
Progress Dialog has no text in Leia

### ISSUE THREAD

**Issue by pizzaboy75** [xperience1080/skin.xperience1080#10]
In Leia, the Progress Dialog has no text. Screenshot attached.
![screenshot003](https://user-images.githubusercontent.com/34249331/36969514-fafd083a-2065-11e8-8728-c974636ebe13.png)

(Reproduce for example: Library -> Clean Library)

**Comment by xhaggi** [comment]
Are you sure this is a skin related issue? We use the same `textbox` control element with id `9` like in Estuary https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/DialogConfirm.xml#L17

**Comment by pizzaboy75** [comment]
Well, it's working in Estuary (Windows 10) for me. Can you reproduce this?

**Comment by xhaggi** [comment]
After a second look it could be something to do with the dublicate textbox control with same id 9. We use a different layout for yes+no, okdialog etc. and progress dialog. I'll change it to use includes instead of just hide it.
