### ISSUE TITLE
Something is missed in osd, always shows spinning

### ISSUE THREAD

**Issue by boot2k3** [xperience1080/skin.xperience1080#12]
This circle is always spinning for PVR, Video and etc.
I don't know what info does it try to receive, but it always spinning
![img_20180305_144724](https://user-images.githubusercontent.com/17234156/36980841-8b3ea8b4-209c-11e8-84a9-637ef5a4f170.jpg)

**Comment by xhaggi** [comment]
It's the weather widget. You need a weather provider (addon) which is configured correctly or uninstall / disable your weather addons.
