### ISSUE TITLE
After skin restart middle part becomes smaller

### ISSUE THREAD

**Issue by boot2k3** [xperience1080/skin.xperience1080#13]
![img_20180305_191033](https://user-images.githubusercontent.com/17234156/36986064-ef62230e-20a9-11e8-90de-082481787b1f.jpg)

**Comment by xhaggi** [comment]
This is a limitation of skin's home screen and could be workaround by going down to power and press down again.

**Comment by h3298** [comment]
**This bug can be fixed, you should leave it OPEN so another developer can work on it.  Xperience will never become a popular skin until this problem is solved.**
