### ISSUE TITLE
Now Playing Menu's produce an empty list for both Video and Music

### ISSUE THREAD

**Issue by sramsay100** [xperience1080/skin.xperience1080#14]
For Kypton v17.6: "Now Playing" menu's produce an empty list for both Video and Music playback. Using 'C' or the library view 'Options' method still provides an empty list.

I have no way to activate repeat and shuffle options which is an additional side effect of this.

I would be grateful for a fix. In the meantime I have been able to fix this by activating Estuary Skin and changing the setting there and then reactivating this skin.

Many thanks in advance.

**Comment by xhaggi** [comment]
Which version do you use (version number please).

**Comment by sramsay100** [comment]
Xhaggi 6.0.6

Hope this helps.

Kind regards

Steve Ramsay

**Comment by xhaggi** [comment]
Sorry for late response I'm bit busy ATM. Could you please provide some screenshots.
