### ISSUE TITLE
Rating format for plugin list items

### ISSUE THREAD

**Issue by JonathanHolvey** [xperience1080/skin.xperience1080#15]
The ratings for audio tracks provided by plugins is displayed as 1.0.0, instead of 1.0.

I assume this is because of an API change between [Jarvis](http://mirrors.kodi.tv/docs/python-docs/16.x-jarvis/xbmcgui.html#ListItem-setInfo) and [Krypton](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14). Previously, the `rating` property that is set using `xbmcgui.listItem.setInfo()` was an integer between 0 and 5, represented as a string. Now, a float value is supported, making the additional `.0` in [`DialogSeekBar.xml`](https://github.com/xperience1080/skin.xperience1080/blob/master/1080i/DialogSeekBar.xml#L308) and [`ViewTypesMusic.xml`](https://github.com/xperience1080/skin.xperience1080/blob/master/1080i/ViewtypesMusic.xml#L390) superfluous.

I can provide a PR to fix this for Krypton and above, however this will leave previous versions without a decimal place.

**Comment by xhaggi** [comment]
Hi @JonathanHolvey it would be nice if you could create a PR  for that issue. Thanks in advance.

**Comment by xhaggi** [comment]
Thank you @JonathanHolvey for your contribution. I've squashed and merged you PR.
