### ISSUE TITLE
Lanscape View - Text Overlapping Issue

### ISSUE THREAD

**Issue by indiusc** [xperience1080/skin.xperience1080#16]
Kodi: 18.0-Leia_alpha2-x64
XPERIENCE1080: Master, Commit:  4a351f1, 1 Jun
AddOn: YouTube

When switching between videos, in lanscape view, the text seems on overlap while moving and selected video

Video screengrab here:
https://imgur.com/a/n4rscdT

thanks

**Comment by xhaggi** [comment]
This problem has something to do with updates in the Kodi core, but should be addressed in Xperience1080. The poster view is also affected.

**Comment by xhaggi** [comment]
Fixed by d6ea1d1dcf573aff482aa47f15e0ff865fc16191
