### ISSUE TITLE
[Pictures widget] support internet URL in "custom image path"

### ISSUE THREAD

**Issue by h3298** [xperience1080/skin.xperience1080#18]
In **Pictures** menu | **Manage custom Home Widget**, allow internet URL for "custom image path"

Example:

![](https://ds.iris.edu/seismon/views/eveday_big//imgs/topMap.eveday_big.gif)
https://ds.iris.edu/seismon/views/eveday_big//imgs/topMap.eveday_big.gif

![](https://ds.iris.edu/seismon/views/eveday//imgs/zmMap.eveday.Europe.gif)
https://ds.iris.edu/seismon/views/eveday//imgs/zmMap.eveday.Europe.gif
______________________________
**Bonus features:**

--> Allow user to set refresh rate for downloading new image (with default at 24 hours)

--> If refresh timer has elapsed and a refresh of the image is pending, do not refresh until **Pictures** menu is traversed by remote control cursor (i.e. no data traffic when device is idle)

**Comment by xhaggi** [comment]
Thank you for your feeback, but this feature request will be rejected.

**Comment by h3298** [comment]
Can you please clarify your decision: 

Dont want to code it, or will not accept a patch from others ?
