### ISSUE TITLE
[Home screen|Add-ons menu] fix redundant add-ons link

### ISSUE THREAD

**Issue by h3298** [xperience1080/skin.xperience1080#21]
In the Xperience home screen Add-ons menu, the shortcut named **[Add-ons]** should open the Kodi location **[Add-ons: Add-on browser]**, not **[Add-ons: Program add-ons]**

(The current setup is redundant because you already have a shortcut for "Program add-ons" under the same menu.)

![add-ons](https://user-images.githubusercontent.com/20834957/42720858-80df915e-86fd-11e8-8c7d-3066d4f7d422.png)

**Comment by xhaggi** [comment]
This is already addressed in Xperience1080 7.x for Kodi v18 (Leia).

![screenshot000](https://user-images.githubusercontent.com/1878991/43365526-616be9ac-932e-11e8-9ae7-843f825ae232.png)
