### ISSUE TITLE
[TV guide] duplicate Estuary guide layout

### ISSUE THREAD

**Issue by h3298** [xperience1080/skin.xperience1080#26]
Remove the wasted space, so more stuff fits on screen

**Xperience**

![xperience tv guide](https://user-images.githubusercontent.com/20834957/42741736-dfca40fc-8882-11e8-899b-8d1929f0346b.png)

**Estuary**

![estuary tv guide suggestion](https://user-images.githubusercontent.com/20834957/42742198-11f82cde-8887-11e8-8eaa-10441353b062.png)

**Comment by xhaggi** [comment]
Thank you for your feeback, but this feature request will be rejected.

**Comment by h3298** [comment]
Can you please clarify your decision: 

Dont want to code it, or will not accept a patch from others ?
