### ISSUE TITLE
MP3 icon fallback as na.png on DialogSeekBar.xml in return of mp3float as codec

### ISSUE THREAD

**Issue by 3XistencE** [xperience1080/skin.xperience1080#28]
On Line 198 of DialogSeekBar.xml
The return from some MP3 files can be also mp3float and this will result to display the icon na.png as fallback instead of Mp3.png
I suggest just to add another png as mp3float.png in order to avoid this problem

**Comment by xhaggi** [comment]
Thank you for the detailed explanation. This will be fixed by 75095b1283ec777e02e7e5f043e4a656401c16c6
