### ISSUE TITLE
videoplaylist only show episodes no tvshows

### ISSUE THREAD

**Issue by b1n4ryj4n** [xperience1080/skin.xperience1080#32]
hi
as soon as i change the big series or movie widget to show a videoplaylist, the episodes are displayed, not just the title of the series, even though the videoplaylist itself works right.

My Series.xsp looks like:
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>Serien</name>
    <match>one</match>
    <rule field="path" operator="contains">
        <value>F:\</value>
    </rule>
    <rule field="path" operator="contains">
        <value>E:\</value>
    </rule>
    <rule field="path" operator="contains">
        <value>J:\</value>
    </rule>
    <rule field="path" operator="contains">
        <value>L:\</value>
    </rule>
</smartplaylist>`

and my other video playlist that should be shown in the series widget:

`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
    <name>Neue Serien</name>
    <match>all</match>
    <rule field="playlist" operator="is">
        <value>Serien</value>
    </rule>
    <limit>25</limit>
    <order direction="descending">dateadded</order>
</smartplaylist>
`
but it shows no tvshows, just episodes o_O

How can i change this? 
Because it works if i open the videoplaylist manually.

**Comment by xhaggi** [comment]
Could you please provide some screenshots to better understand your issue.

**Comment by b1n4ryj4n** [comment]
It was opened Feb 6, 2019 and i forgot i have this issue still open^^
I dont use Kodi anymore so i close it.
