### ISSUE TITLE
TV Shows Info List View: Missing Right Info panel

### ISSUE THREAD

**Issue by Firelfy** [xperience1080/skin.xperience1080#6]
Hi!

I'm missing the info panel when I use the info list view-type.

I am currently using the plexkodiconnect addon (PKC) as a kodi 'backend' for my media and just reset my TV Library inside plex, so I'm hoping that's not the issue (especially considering during other view-types I can see synopsis etc).

Here's a picture of what's going on:

![](http://i.imgur.com/QhkzXyi.jpg)

Hopefully this helps, great product btw!

**Comment by Firelfy** [comment]
Possibly related to this?
[https://github.com/xperience1080/skin.xperience1080/commit/da025ad3659c55bb47f192c77272f6908849fac5?diff=split](url)

**Comment by xhaggi** [comment]
Should be fixed.
