### ISSUE TITLE
Notification Behaviour During Fullscreen video

### ISSUE THREAD

**Issue by drwggm** [xperience1080/skin.xperience1080#7]
I was playing around with JSONRPC, and noticed some unintended (maybe) behavior.

Reproducible Example:

` curl -u foo:bar -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"id":1,"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Test","message":"Line 1 \n Line 2"}}' http://kodiip:8080/jsonrpc `

I am using a nightly build of Krypton.  I had a similar problem before hand, I believe even in 16.x

Running the example in Full Screen video mode will display Title and Line 1, but nothing after.

Doing it in one of the menus displays Title, Line 1 and Line 2.  Other skins seem to have this behavior even in full screen video.

Love the skin otherwise. Let me know if I'm missing something obvious.
Thanks.

**Comment by xhaggi** [comment]
Could you please try this again with the latest version of Xperience1080 and Kodi v18 (Leia) alpha builds.
